name: Déploiement Serveur Web Nginx

on:
  push:
    branches: [ main ]

jobs:
  deploy-infra:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - os2
    outputs:
      vm_ip: ${{ steps.deploy.outputs.ip }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Rendre le script exécutable 
        run: chmod +x scripts/deploy_vm.sh

     
      - name: Déploiement du serveur Nginx
        id: deploy
        run: |
          VM_NAME=$(yq -r .vm.name intent.yaml)
          ./scripts/deploy_vm.sh $VM_NAME

 
      - name: Installation Nginx sur serveurs Web
        run: |
          FLOATING_IP=$(yq -r .vm.floating_ip intent.yaml)
          sudo rm ~/.ssh/known_hosts
          ssh -i ~/.ssh/ostack fred@$FLOATING_IP 'bash -s' < scripts/install_nginx.sh
